/*
 * This source file was generated by the Gradle 'init' task
 */
package librarymanagement;
import librarymanagement.Service.LibraryService;
import java.util.Scanner;

import librarymanagement.Entity.Book;
public class App {
    

    public static void main(String[] args) {
         Scanner scanner = new Scanner(System.in);
        LibraryService library = new LibraryService();
        int choice;

        do {
            System.out.println("\n===== Library Menu =====");
            System.out.println("1. Add Book");
            System.out.println("2. Borrow Book");
            System.out.println("3. Return Book");
            System.out.println("4. View All Books");
            System.out.println("5. Exit");
            System.out.print("Enter your choice: ");
            choice = scanner.nextInt();
            scanner.nextLine(); // consume newline

            switch (choice) {
                case 1 -> {
                    System.out.print("Enter title: ");
                    String title = scanner.nextLine();
                    System.out.print("Enter author: ");
                    String author = scanner.nextLine();
                    library.addBook(new Book(title, author));   //created a new book object
                }
                case 2 -> {
                    System.out.print("Enter book title to borrow: ");
                    String title = scanner.nextLine();
                    library.BorrowBook(title);
                }
                case 3 -> {
                    System.out.print("Enter book title to return: ");
                    String title = scanner.nextLine();
                    library.ReturnBook(title);
                }
                case 4 -> library.showBooks();
                case 5 -> System.out.println("👋 Exiting system. Goodbye!");
                default -> System.out.println("❗ Invalid choice. Try again.");
            }
        } while (choice != 5);

        scanner.close();
    }
} 
    

